[package]
name = "password-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
clap = { version = "4.5.49", features = ["derive"] }
sqlx = { version = "0.8", features = [ "sqlite", "runtime-tokio", "tls-native-tls" ] }
tokio = { version = "1.20.0", features = ["full"] }
